issy_web/auto/urls.py
from django.conf.urls import url

from . import views

app_name='auto'


urlpatterns = [

url(r'^$',views.AutoListView.as_view(),name="auto_list"),
url(r'^(?P<pk>\d+)$',views.AutoDetailView.as_view(),name='auto_detail'),
url(r'^new/$',views.CreateAutoView.as_view(),name="auto_crear"),
url(r'^(?P<pk>\d+)/edit/$',views.AutoUpdateView.as_view(),name="auto_edit"),
url(r'^(?P<pk>\d+)/remove/$',views.AutoDeleteView.as_view(),name="auto_remove"),
url(r'^(?P<pk>\d+)/ofertar/$',views.AutoOfertar,name="auto_ofertar"),
url(r'^ofertados/$',views.AutoOfertados,name="auto_ofertados"),
url(r'^sinofertar/$',views.AutoSinOfertar,name="auto_sin_ofertar"),
url(r'^contratos/$',views.AutoContratos.as_view(),name="contratos"),
url(r'^contratar/(?P<owner>\w+)/(?P<auto>\w+)$',views.AutoContratar,name="contratar"),
url(r'^ofertas_hacia_mi/$',views.GetContratosForMe,name="ofertas_hacia_mi"),
url(r'^ofertas_hacia_otros/$',views.GetContratosToOther,name="ofertas_hacia_otros"),
url(r'^aceptar_contrato/(?P<pk>\d+)/$',views.AcceptContract,name="aceptar_contrato"),
url(r'^finalizar_contrato/(?P<pk>\d+)/$',views.FinishContract.as_view(),name="finalizar_contrato"),


]

issy_web/auto/models.py
from django.db import models
from django.contrib.auth import get_user_model
from django.core.urlresolvers import reverse

User = get_user_model()

HIRED_STATUS=(
    ('1', 'espera'),
    ('2', 'aceptado'),
    ('3', 'finalizado'),

)

# Create your models here.

class Auto(models.Model):
	user = models.ForeignKey("auth.User",null=True)
	modelo= models.CharField(max_length=264)
	plazas= models.CharField(max_length=264)
	aire_acondicionado= models.CharField(max_length=264)
	tipo_transmision= models.CharField(max_length=264)
	lugar_recogida= models.CharField(max_length=264)
	precio= models.FloatField()
	jornada= models.IntegerField()
	is_alquiled= models.BooleanField(default=False)
	def __str__(self):
		return self.modelo

	def get_absolute_url(self):
		return reverse("auto:auto_list")



class Contrato(models.Model):
	User_alquila=models.ForeignKey("auth.User",null=True,related_name="user_alquila")
	User_contrata=models.ForeignKey("auth.User",null=True,related_name="user_contrata")
	auto =models.ForeignKey(Auto,null=True,related_name="auto_contrata")
	hired_status=models.CharField(max_length = 1, choices = HIRED_STATUS,
	null = False, default = HIRED_STATUS[0][0])
	#class Meta:
	#	unique_together = (('User_alquila', 'User_contrata','auto'),)

class Reviews(models.Model):
	contrato=models.ForeignKey(Contrato,null=True)
	comment = models.TextField(null=True)
	rating = models.IntegerField(null=False)

	def get_absolute_url(self):
		return reverse("auto:contratos")

issy_web/auto/forms.py
from django import forms
from django.core import validators

from .models import Auto

class AutoForm(forms.ModelForm):
	class Meta():
		model = Auto
		exclude = ('user','is_alquiled')
		fields ="__all__"


class NewAuto(forms.ModelForm):
	class Meta():
		model= Auto
		fields ="__all__"

issy_web/auto/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.utils import timezone

from auto.forms import AutoForm
from conductor.forms import ReviewForm

from django.urls import  reverse_lazy
from django.contrib.auth.decorators import login_required
from django.contrib.auth.mixins import LoginRequiredMixin
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from django.views.decorators.http import require_http_methods
from django.http import HttpResponse
from .models import Auto,Contrato
from django.contrib.auth import get_user_model
from django.db import IntegrityError
from django.db.models import Q
from conductor.forms import ReviewForm
from auto.models import Reviews
from django.core.urlresolvers import reverse
User = get_user_model()
# Create your views here.


class AutoListView(ListView):
	model = Auto

	def get_queryset(self):
		return Auto.objects.filter(user=self.request.user).order_by('-precio')



class AutoDetailView(DetailView):
	model = Auto

class CreateAutoView(LoginRequiredMixin,CreateView):

	login_url ="/login/"
	redirect_field_name = "auto/auto_detail.html"
	form_class= AutoForm
	model = Auto
	def form_valid(self, form):
		self.object = form.save(commit=False)
		print (self.request.user.username)
		self.object.user = self.request.user
		self.object.save()
		return super().form_valid(form)


class AutoUpdateView(LoginRequiredMixin,UpdateView):

	login_url ="/login/"
	redirect_field_name = "auto/auto_detail.html"
	form_class= AutoForm
	model = Auto


class AutoDeleteView(LoginRequiredMixin,DeleteView):
	model = Auto
	success_url = reverse_lazy("auto:auto_list")



class AutoContratos(LoginRequiredMixin,ListView):
	model= Contrato
	template_name = 'auto/contrato_list.html'
	def get_context_data(self):
		mContrato= Contrato.objects.filter(Q(User_contrata=self.request.user)| Q(User_alquila=self.request.user))
		dict_res={'contrato_list':mContrato,'is_for_me':False}
		return dict_res

@require_http_methods(["GET"])
def GetContratosForMe(request):
	mContrato= Contrato.objects.filter(User_alquila=request.user)
	dict_res={'contrato_list':mContrato,'is_for_me':True}
	return render(request,'auto/contrato_list.html',dict_res)

@require_http_methods(["GET"])
def GetContratosToOther(request):
	mContrato= Contrato.objects.filter(User_contrata=request.user)
	dict_res={'contrato_list':mContrato,'is_for_me':False}
	return render(request,'auto/contrato_list.html',dict_res)

@require_http_methods(["GET"])
def AcceptContract(request,pk):
	Contrato.objects.filter(pk=pk).update(hired_status='2')
	mContrato= Contrato.objects.filter(User_contrata=request.user)
	dict_res={'contrato_list':mContrato,'is_for_me':False}
	return render(request,'auto/contrato_list.html',dict_res)


'''
@require_http_methods(["GET"])
def FinishContract(request,pk):
	Contrato.objects.filter(pk=pk).update(hired_status='3')
	mContrato= Contrato.objects.filter(User_contrata=request.user)
	dict_res={'contrato_list':mContrato,'is_for_me':False}
	return render(request,'auto/contrato_list.html',dict_res)
'''

class FinishContract(LoginRequiredMixin,CreateView):

	form_class = ReviewForm
	model = Reviews
	template_name="conductor/review_create.html"

	def form_valid(self, form):
		self.object = form.save(commit=False)
		print (self.kwargs)
		form.instance.contrato = Contrato.objects.get(pk=self.request.session['contrato_pk'])
		form.instance.contrato.hired_status='3'
		form.instance.contrato.save()
		form.instance.contrato.auto.is_alquiled=False
		form.instance.contrato.auto.save()
		self.object.save()
		return super().form_valid(form)
	def dispatch(self, request, *args, **kwargs):
		# parse the request here ie.
		#self.foo = request.GET.get('foo', False)
		print (self.kwargs['pk'])
		request.session['contrato_pk'] = self.kwargs['pk']
		# call the view
		return super(FinishContract, self).dispatch(request, *args, **kwargs)





@login_required
def AutoOfertar(request,pk):
	p= Auto.objects.filter(pk=pk).update(is_alquiled=True)
	print(p)
	ofertas=Auto.objects.filter(is_alquiled=True,pk=pk)

	return render(request,'auto/auto_list.html',{'ofertas':ofertas})


@login_required
def AutoOfertados(request):

	ofertas=Auto.objects.filter(is_alquiled=True,user=request.user)

	return render(request,'auto/auto_list.html',{'auto_list':ofertas})


@login_required
def AutoSinOfertar(request):

	ofertas=Auto.objects.filter(is_alquiled=False,user=request.user)

	return render(request,'auto/auto_list.html',{'auto_list':ofertas})


@login_required
@require_http_methods(["GET"])
def AutoContratar(request,owner,auto):

	print (owner)
	print (auto)
	owner = User.objects.get(username=owner)
	print (owner)
	print(auto)
	Auto_status=Auto.objects.get(is_alquiled=False,user=owner,pk=auto)
	if Auto_status == None:
		return HttpResponse('auto already hired')
	Auto.objects.filter(user=owner,pk=auto).update(is_alquiled=True)
	contract = Contrato(User_alquila=owner,User_contrata=request.user,auto=Auto_status)
	try:
		contract.save()
		return redirect('auto:contratos')
	except IntegrityError as e:
		return HttpResponse('error reference key')


	

issy_web/auto/templates/auto/_auto.html
{% load staticfiles %}

<div class="row">
	
			<div class="col-md-4">
				<a href="{% url 'conductor:info_auto_detalle' pk=acc.pk%}"><img src="{% static 'img/car.jpg' %}" class="img-thumbnail"></a>
				
			</div>
			<div class="col-md-4">
				<h2>{{acc.modelo}}</h2>
				<p><strong>plazas: </strong>{{acc.plazas}}</p>
				<p><strong>Aire Acondicionado: </strong>{{acc.aire_acondicionado}}</p>
				<p><strong>Tipo Transmision: </strong>{{acc.tipo_transmision}}</p>
				<p><strong>Lugar Recogida: </strong>{{acc.lugar_recodiga}}</p>
			</div>
			<div class="col-md-4">
				<h2> Precio por jornada de {{acc.jornada}} horas</h2>
				<h1>S/.{{acc.precio}}</h1>
			</div>
	</div>

issy_web/auto/templates/auto/auto_base.html
{% extends "base.html" %}

{% block content %}

<div class="container micontenido">
	
		{% block auto_content %}{% endblock %}
	
</div>

{% endblock %}

issy_web/auto/templates/auto/auto_confirm_delete.html
{% extends "auto/auto_base.html" %}


{% block auto_content %}
<h1><strong>¿estas seguro que quieres borrar este auto?</strong></h1>

<div class="posts">
	{% include "auto/_auto.html" with acc=object hide_delete=True %}
</div>

<form method="POST">
	{% csrf_token %}
	<input type="submit" value="Confirm Delete" class="btn btn-danger btn-large">
	<a href="{% url 'auto:auto_list' %}" class="btn btn-simple btn-large btn-default">Cancel</a>
</form>

{% endblock %}

issy_web/auto/templates/auto/auto_form.html
{% extends "auto/auto_base.html" %}

{% load bootstrap3 %}

{% block auto_content %}
<h4>Crear Nuevo Auto</h4>
<form method="POST" id="postForm">
	{% csrf_token %}
	{% bootstrap_form form %}
	<input type="submit" value="Post" class="btn btn-primary btn-large">
</form>
{% endblock %}

issy_web/auto/templates/auto/auto_list.html
{% extends "auto/auto_base.html" %}
{% load staticfiles%}

{% block auto_content%}
<h1>LISTA DE AUTOS</h1>
<div class="col-md-12">
	<div class="btn-group">
		<a class="btn btn-success" href="{% url 'auto:auto_crear' %}">
			<span class="glyphicon glyphicon-pencil"></span><strong>Crear Auto</strong>
		</a>
		<a class="btn btn-default" href="{% url 'auto:auto_sin_ofertar' %}">
			<span class="glyphicon glyphicon-eye-close"></span><strong>Autos Sin ofertar</strong>
		</a>
		<a class="btn btn-warning" href="{% url 'auto:auto_ofertados' %}">
			<span class="glyphicon glyphicon-eye-open"></span><strong>Autos Ofertados</strong>
		</a>
		<a class="btn btn-success" href="{% url 'auto:auto_list' %}">
			<span class="glyphicon glyphicon-th-list"></span><strong>Toda la lista</strong>
		</a>
	</div>
</div>
{% for acc in auto_list %}
<div class="col-md-12">
	<a class="btn btn-primary pull-right" href="{% url 'auto:auto_edit' pk=acc.pk %}">
		<span class="glyphicon glyphicon-pencil"></span><strong>editar</strong>
	</a>
	<a class="btn btn-warning pull-right" href="{% url 'auto:auto_remove' pk=acc.pk %}">
		<span class="glyphicon glyphicon-remove"></span><strong>Eliminar</strong>
	</a>
	{% if acc.is_alquiled == False%}
	<a class="btn btn-info pull-right" href="{% url 'auto:auto_ofertar' pk=acc.pk %}">
		<span class="glyphicon glyphicon-remove"></span><strong>Ofertar</strong>
	</a>
	{%endif%}
</div>
{% include "auto/_auto.html"%}
{%endfor%}

{% endblock %}

issy_web/auto/templates/auto/auto_ofertas.html
{% extends "auto/auto_base.html" %}
{% load staticfiles%}

{% block auto_content%}
<h1>MIS AUTOS EN OFERTA</h1>
<!--div class="col-md-12">
	<a class="btn btn-success" href="{% url 'auto:auto_crear' %}">
		<span class="glyphicon glyphicon-pencil"></span><strong>Crear Auto</strong>
	</a>
</div-->
{% for acc in ofertas %}
	<div class="col-md-12">
	<a class="btn btn-primary pull-right" href="{% url 'auto:auto_edit' pk=acc.pk %}">
		<span class="glyphicon glyphicon-pencil"></span><strong>editar</strong>
	</a>
	<a class="btn btn-warning pull-right" href="{% url 'auto:auto_remove' pk=acc.pk %}">
		<span class="glyphicon glyphicon-remove"></span><strong>Eliminar</strong>
	</a>
	</div>
	{% include "auto/_auto.html"%}
{%endfor%}

{% endblock %}

issy_web/auto/templates/auto/contrato_list.html
{% extends 'base.html' %}

{%  block content %}

<div class="container micontenido">
	<h1>mis contratos</h1>
	<div class="col-md-12">
		<div class="btn-group">
			<a class="btn btn-success" href="{% url 'auto:ofertas_hacia_mi' %}">
				<span class="glyphicon glyphicon-eye-close"></span><strong>Hacia mi</strong>
			</a>
			<a class="btn btn-primary" href="{% url 'auto:ofertas_hacia_otros' %}">
				<span class="glyphicon glyphicon-eye-open"></span><strong>Hechos a otros</strong>
			</a>
		</div>
	</div>
	<div class="col-md-12">
		<div class="table-responsive">

			<table class="table table-hover table-striped">
				<thead>
					<tr>
						<th>
							{% if is_for_me %}
							Interesado
							{%else%}
							Propietario
							{%endif%}
						</th>
						<th>Auto</th>
						<th>Estado</th>
						{% if is_for_me %}
						<th></th>
						{%endif%}
					</tr>
				</thead>
				<tbody class="table-hover">
					{% for contrato in contrato_list%}

					<tr>
						<td>
							{%if is_for_me%}
							{{contrato.User_contrata.conductor.nombre}} {{contrato.User_contrata.conductor.apellido}}
							{%else%}
							{{contrato.User_alquila.conductor.nombre}} {{contrato.User_alquila.conductor.apellido}}
							{%endif%}
						</td>
						<td>
							{{contrato.auto}}
						</td>
						<td>{{contrato.get_hired_status_display }}
						</td>
						
						{% if is_for_me and contrato.hired_status == "1" %}
						<td>
							<a class="btn btn-primary" href="{% url 'auto:aceptar_contrato' pk=contrato.pk %}">Aceptar</a>
						</td>
						{%elif is_for_me and contrato.hired_status != "3" %}
						<td>
							<a class="btn btn-success" href="{% url 'auto:finalizar_contrato' pk=contrato.pk  %}">Finalizar</a>
						</td>
						{%endif%}

					</tr>

					{%endfor%}
				</tbody>
			</table>
		</div>
	</div>
</div>
{% endblock %}