issy_web/conductor/urls.py
from django.conf.urls import url
from conductor import views

app_name = 'conductor'
urlpatterns = [
url(r'^$',views.AlquilarAuto.as_view(),name="alquilar_auto"),
url(r'^buscar_autos/$',views.alquilar_auto_lista,name="buscar_autos"),
url(r'^home_conductor/$',views.HomeConductor.as_view(),name="home_conductor"),
url(r'^duenho/home_duenho$',views.HomeDuenho.as_view(),name="home_duenho"),
url(r'^conductor/registro_conductor$',views.ConductorCreate.as_view(),name = "registro_conductor"),
url(r'^conductor_info/$',views.ConductorInfo,name="conductor_info"),
url(r'^perfil/(?P<pk>\d+)/edit/$',views.ConductorUpdate.as_view(),name="perfil_edit"),
url(r'^perfil/new/$',views.ConductorProfileCreate.as_view(),name="perfil_crear"),
url(r'^$',views.Index.as_view(),name="index"),
url(r'^info_auto/(?P<pk>\d+)/detalle/$',views.info_auto_detalle,name="info_auto_detalle"),
url(r'^conductor/historial_conductor$',views.HistoConductor.as_view(),name="historial_conductor"),

]

issy_web/conductor/models.py
from django.db import models
from issy_web.constants import ESTADO_CIVIL
import datetime
from django.core.urlresolvers import reverse
# Create your models here.

from django.contrib.auth import get_user_model
User = get_user_model()


class Conductor(models.Model):
	#user = models.OneToOneField(User, on_delete=models.CASCADE,primary_key=True,default='')
	user = models.OneToOneField("auth.User")
	nombre = models.CharField(max_length=264,blank=False,null=False)
	apellido = models.CharField(max_length=264,blank=False,null=False)
	estrellas = models.IntegerField(default=0,blank=False,null=False)
	estado = models.CharField(max_length=20)
	edad = models.IntegerField(blank=False,null=False)
	estado_civil = models.CharField(max_length = 1, choices = ESTADO_CIVIL, blank = False,
	null = False, default = ESTADO_CIVIL[0][0])
	ciudad = models.CharField(max_length=50,blank=False,null=False)
	inicio_app = models.DateField(default=datetime.date.today,blank=False,null=False)
	total_viajes = models.IntegerField(default=0,blank=False,null=False)
	tipo_licencia = models.CharField(max_length=8,blank=False,null=False)
	vencimiento_licencia = models.DateField(blank=False,null=False)
	telefono = models.IntegerField(blank=False,null=False)


	def get_absolute_url(self):
		return reverse("conductor:conductor_info")


	

issy_web/conductor/forms.py
from django import forms
from django.core import validators

from conductor.models import  Conductor
from auto.models import Reviews



class ConductorForm(forms.ModelForm):
	class Meta():
		model = Conductor
		exclude = ('user',)
		fields ="__all__"


class ReviewForm(forms.ModelForm):
	class Meta():
		model = Reviews
		fields ="__all__"
		exclude = ('contrato',)
		

'''	def get_form_kwargs(self, **kwargs):
		form_kwargs = super(TestCreateView, self).get_form_kwargs(**kwargs)
		form_kwargs["pk"] = self.request.user
		return form_kwargs
'''

issy_web/conductor/views.py
from django.shortcuts import render,get_object_or_404,redirect
from django.urls import reverse_lazy
#necesario para restricciones en logeo
from django.contrib.auth.decorators import login_required

#necesario para trabajar con plantillas(CRUD)
from django.views.generic import (TemplateView,ListView,DetailView,CreateView,UpdateView,DeleteView)
from braces.views import SelectRelatedMixin
from django.views import generic
from .forms import ConductorForm
from conductor.models import Conductor
from auto.models import Reviews
from auto.models import Auto
from django.contrib.auth.mixins import LoginRequiredMixin

from django.contrib.auth import get_user_model
User = get_user_model()


# Create your views here.

class AlquilarAuto(TemplateView):
	template_name= 'conductor/alquilar_auto.html'

class HomeConductor(TemplateView):
	template_name= 'conductor/home_conductor.html'

class HomeDuenho(TemplateView):
	template_name= 'duenho/home_duenho.html'


class HistoConductor(TemplateView):
	template_name= 'conductor/historial_conductor.html'

def info_auto_detalle(request,pk):

	Webpage_list = Auto.objects.get(pk=pk)
	return render(request,'conductor/info_auto.html',{'info_auto_detalle':Webpage_list})



 

def ConductorInfo(request):
	try:
		conductor = Conductor.objects.get(user=request.user)
		reviews = Reviews.objects.filter(contrato__User_contrata=request.user)
		print (reviews)
	except Conductor.DoesNotExist:
		conductor =None
	return render(request,'conductor/conductor_info.html',{'conductor':conductor,'reviews':reviews})




class ConductorCreate(CreateView):
	model = Conductor
	form_class = ConductorForm
	template_name = 'registration/registro_conductor.html'
	success_url = reverse_lazy('home_conductor')

class Index(TemplateView):
	template_name = 'index.html'



class ConductorProfileCreate(LoginRequiredMixin,CreateView):
	form_class = ConductorForm
	model = Conductor
	redirect_field_name = "conductor/conductor_info.html"

	def form_valid(self, form):
		self.object = form.save(commit=False)
		self.object.user_sender = self.request.user
		self.object.save()
		return super().form_valid(form)

class ConductorUpdate(LoginRequiredMixin,UpdateView):

	form_class = ConductorForm
	model = Conductor
	redirect_field_name = "conductor/conductor_info.html"




@login_required
def alquilar_auto_lista(request):

	Webpage_list = Auto.objects.exclude(user=request.user).filter(is_alquiled=False).order_by('precio')
	date_dict ={'access_records':Webpage_list,'query_ok':"True"}

	print (Webpage_list)
	return render(request,'conductor/alquilar_auto.html',context=date_dict)

issy_web/conductor/templates/base.html
<!DOCTYPE html>
{% load staticfiles%}
<html lang="en">
<head>
	<meta charset="utf-8">
	<meta http-equiv="X-UA-Compatible" content="IE=edge">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<!-- The above 3 meta tags must come first in the head; any other head content must come *after* these tags -->
	<meta name="description" content="">
	<meta name="author" content="">
	<link rel="icon" href="../../favicon.ico">
	<title>IssyCar: Alquiler y contactos de conductores</title>
	<!-- Latest compiled and minified CSS -->
	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
	

	<script type="text/javascript" src="https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.23.2/js/medium-editor.min.js"></script>
	<link rel="stylesheet" type="text/css" href="https://cdnjs.cloudflare.com/ajax/libs/medium-editor/5.23.2/css/medium-editor.min.css">


	<link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/font-awesome/4.7.0/css/font-awesome.min.css" crossorigin="anonymous">


	

	<link rel="stylesheet" type="text/css" href="{% static 'css/estilos_general.css'%}">
	<link rel="stylesheet" type="text/css" href="{% static 'css/style_conductor.css'%}">
	<link href="https://fonts.googleapis.com/css?family=Montserrat|Russo+One" rel="stylesheet">

	<!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/html5shiv/3.7.3/html5shiv.min.js"></script>
    <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
<![endif]-->
</head>
<body>
	<nav class="navbar navbar-default navbar-fixed-top">
		<div class="container">
			<div class="navbar-header">
				<button type="button" class="navbar-toggle collapsed" data-toggle="collapse" data-target="#navbar" aria-expanded="false" aria-controls="navbar">
					<span class="sr-only">Toggle navigation</span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
					<span class="icon-bar"></span>
				</button>
				<a class="navbar-brand em-text" href="{% url 'conductor:buscar_autos' %}">Issy Car</a>
			</div>
			<div id="navbar" class="collapse navbar-collapse">
				<ul class="nav navbar-nav">
					
					<li><a href="/">Inicio</a></li>
					{% if user.is_authenticated %}
					<li><a href="{% url 'conductor:conductor_info' %}">Mi perfil</a></li>
					<li><a href="{% url 'auto:auto_list'%}">Mis autos</a></li>
					<li><a href="{% url 'conductor:alquilar_auto' %}">Buscar Auto</a></li>
					<li><a href="{% url 'auto:contratos' %}">Contratos</a></li>
				</ul>
				<ul class="nav navbar-nav navbar-right">
					<li class="dropdown active">
					<a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button" aria-expanded="false"><strong>{{user.username}}</strong> <span class="caret"></span></a>
					
					<ul class="dropdown-menu">
					<li><a href="{% url 'accounts:logout'%}">Salir</a></li>
					</ul>
				</ul>

				{% else %}
				<li><a href="{% url 'conductor:alquilar_auto' %}">Buscar Auto</a></li>
				<li><a href="{% url 'accounts:signup' %}" class="btn btn-simple">Registrarse</a></li>
				<li><a href="{% url 'accounts:login' %}" class="btn btn-simple">Ingresar</a></li>
			</ul>
			{% endif%}

		</div><!--/.nav-collapse -->
	</div>
</nav>

{% block content%}
{% endblock %}

<footer class="navbar-bottom">
	<div class="container">
		<div class="row">
			<div class="col-md-6 col-xs-12">
				<ul>
					<li><a href="#">Home</a></li>
					<li><a href="#">About</a></li>
					<li><a href="#">Contact</a></li>
					<li><a href="#">Privacy Policy</a></li>
				</ul>
			</div>
			<div class="col-md-6 col-xs-12">
				<p>Copyright &copy; 2017 All right reserved</p>
			</div>
		</div>
	</div>
</footer>
      <!-- Bootstrap core JavaScript
      	================================================== -->
      	<!-- Placed at the end of the document so the pages load faster -->
      	<script src="https://ajax.googleapis.com/ajax/libs/jquery/1.12.4/jquery.min.js"></script>
      	<!-- Latest compiled and minified JavaScript -->
      	<script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>
      </body>
      </html>

issy_web/conductor/templates/conductor/_review.html
{% load staticfiles%}

    <div class="row">
        <div class="col-md-1">
            <img src="{% static 'img/icon-male.png' %}" class="img-thumbnail">
        </div>
        <div class="col-md-11">
            <h3>{{review.contrato.User_alquila.conductor.nombre}} {{review.contrato.User_alquila.conductor.apellido}}</h3>
            {% for x in ""|ljust:review.rating %}

            <span class="fa fa-star checked"></span>
            {%endfor%}
            <p>{{review.comment}}</p>
        </div>
    </div>

issy_web/conductor/templates/conductor/alquilar_auto.html
{% extends "../base.html"%}
{% load staticfiles %}
{% block content %}

<div class="container">
	<div class="jumbotron">

		<h1>Alquiler de <i class="fa fa-car" aria-hidden="true"></i>
		En el Peru</h1>

		<form method="post" action ="{% url 'conductor:buscar_autos' %}" >
			{% csrf_token %} 
			<div class="row">
				<div class="col-md-6">
					<div class="row">
						<div class="form-group col-md-12">
							<label for="IdLugarRecogo">Lugar de Recogida</label>
							<input type="text" class="form-control" id="IdLugarRecogo" name="lugarRecogo" placeholder="Lugar Recogo">
						</div>
						<div class="form-group col-md-12">
							<label for="IdJornada">Jornada</label>
							
							<select class="form-control" name="jornada">
								<option selected>Choose...</option>
								<option value="12">Medio Turno</option>
								<option value="24">Tiempo Completo</option>
							</select>
						</div>
						
					</div>
				</div>
				<div class="col-md-6">
					<div class="row">
						<div class="form-group col-md-12">
							
							<label for="IdModelo">Modelo</label>
							<input type="text" class="form-control" id="IdModelo" name="modelo" placeholder="Modelo">
						</div>
						<div class="form-group col-md-12">

							<label for="IdPrecio">Precio Maximo</label>
							<input type="number" class="form-control" id="IdPrecio" name="precio" placeholder="precio" pattern="^\d+(?:\.\d{1,2})?$" step="0.01" >
						</div>
						<div class="form-group col-md-12">

						</div>
					</div>
				</div>
				
			</div>
			<div class=row>
				<div class="col-md-12">
					<button type="submit" class="btn btn-primary pull-right">Submit</button>
				</div>
			</div>
		</form>
	</div>


	<!-- modelo= models.CharField(max_length=264)
	plazas= models.CharField(max_length=264)
	aire_acondicionado= models.CharField(max_length=264)
	tipo_transmision= models.CharField(max_length=264)
	lugar_recodiga= models.CharField(max_length=264)
	precio= models.FloatField()
	jornada= models.IntegerField(max_length=264)
	is_alquiled= models.BooleanField() -->
	{% if access_records %}
	<section>
		<h2>Recomendados</h2>
		{% for acc in access_records %}
		{% include "auto/_auto.html"%}
		{% endfor %}
	</section>

	{% endif %}
</div>

{% endblock%}

issy_web/conductor/templates/conductor/conductor_form.html
{% extends "../base.html"%}
{% load bootstrap3 %}
{% block content %}


<div class="container">
	<h1>Modificando usuario: {{user.username}}</h1>
	<form class="post-form" method="POST">
		{%  csrf_token %}
		{% bootstrap_form form %}
		<button type="submit" class="save btn btn-default">Save</button>
	</form>

</div>

<script type="text/javascript">
	var editor = new MediumEditor(".editable");
</script>
{% endblock%}

issy_web/conductor/templates/conductor/conductor_info.html
{% extends "../base.html"%}
{% load staticfiles %}
{% block content %}
<section class="conductor-info">
    <div class="container">
        <div class="row">
            <div class="col-md-2">
                <img src="{% static 'img/icon-male.png' %}" class="img-thumbnail">
            </div>
            <div class="col-md-10">
                <div class="row">
                    {% if user.is_authenticated %}
                    {% if conductor %}
                    <a class="btn btn-primary" href="{% url 'conductor:perfil_edit' pk=user.conductor.id %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    {% else%}
                    <a class="btn btn-success" href="{% url 'conductor:perfil_crear' %}">
                        <span class="glyphicon glyphicon-pencil"></span>
                    </a>
                    {%endif%}
                    {% endif%}
                </div>
                <div class = "row">
                    <h1>{{conductor.nombre}} {{conductor.apellido}}</h1>

                </div>
                <div class = "row">
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                    <span class="fa fa-star checked"></span>
                </div>
                <hr>

                <div class = "row">
                    <div class="col-md-4">
                      <p><strong>Edad:</strong>{{conductor.edad}}</p>
                  </div>
                  <div class="col-md-4">
                      <p><strong>Estado civil:</strong>{{conductor.estado_civil}}</p>
                  </div>
                  <div class="col-md-4">
                      <p><strong>Ciudad:</strong>{{conductor.ciudad}}</p>
                  </div>


              </div>
          </div>
      </div>
      <div class="row">
        <div class="col-md-6">
            <h2>Experiencia</h2>
            <p><strong>Inicio en la app:</strong>{{conductor.inicio_app}}</p>
            <p><strong>Número de viajes:</strong>{{conductor.total_viajes}}</p>
        </div>
        <div class="cold-md-6">
            <h2>Licencia</h2>
            <p><strong>Tipo:</strong>{{conductor.tipo_licencia}}</p>
            <p><strong>Fecha de vencimiento:</strong>{{conductor.vencimiento_licencia}}</p>
        </div>
    </div>
    <hr>
    <h1> Reseñas</h1>

{%for review in reviews %}
{% include "conductor/_review.html"%}
{%endfor%}

   

</section>
{% endblock %}

issy_web/conductor/templates/conductor/home_conductor.html
{% extends "../base.html"%}
{% load staticfiles %}
{% block content %}

<div class="container" >
	<div class="jumbotron" id="contain">

		
		<form method="post" action ="" >
		{% csrf_token %}
			 <div class="row">
				 <div class="col-md-4">
				 	<h1>Estado</h1>	
			 	 </div>
			 	 <div class="col-md-4">
			 	 </div>
			 	 <div class="col-md-2">
				 </div>
			 	 <div class="col-md-1">
				 </div>
			 	 <div class="col-md-1">
					  <h1><i class="fa fa-refresh" aria-hidden="true"></i></h1>
			 	 </div>
			</div>

			<div class="row">
				 <div class="col-md-6">
				 	<div class="row">
				 		<div class="col-md-6">
				 			<a href=""><img src="{% static 'img/perfil.png' %}" class="img-thumbnail" style="width: 75%"></a>
				 		</div>
				 		<div class="col-md-6">
				 			<h2>Christian Flores</h2>
				 		</div>
				 	</div>
			 	 </div>
			 	 <div class="col-md-6">
				 	 <div class="row">
					 	 <div class="col-md-4">
					 	 	
					 	 </div>
					 	 <div class="col-md-4">
					 	 	<h2>Estado</h2>
					 	 	
					 	 </div>
					 	 <div class="col-md-4">
					 	 </div>
					 </div>
					 <div class="row">
					 	 <div class="col-md-4">
					 	 	<h2>Dueño :</h2>
					 	 </div>
					 	 <div class="col-md-8">
					 	 	<h2>Christian Flores</h2>
					 	 </div>
					 	 
					 </div>
					  <div class="row">
					 	 <div class="col-md-4">
					 	 	<h2>Jornada :</h2>
					 	 </div>
					 	 <div class="col-md-8">
					 	 	<h2>12 horas</h2>
					 	 </div>
					 </div>
				 </div>
			 	 
			</div>
			<div class="row">


				<div class="col-md-6">
					<div class="row">
					<div class= "col-md-1">
					</div>
			 		<div class="col-md-11">
			 		<i class="fa fa-star-o" aria-hidden="true"></i>
			 		<i class="fa fa-star-o" aria-hidden="true"></i>
			 		<i class="fa fa-star-o" aria-hidden="true"></i>
			 		<i class="fa fa-star-o" aria-hidden="true"></i>
			 		<i class="fa fa-star-o" aria-hidden="true"></i>
			 		
			 		</div>
			 		</div>
			 	</div>
			 	<div class="col-md-6">
			 		
			 	</div>
			 </div>
			
<!--
			<div class=row>
				<div class="col-md-12">
					<button type="submit" class="btn btn-primary pull-right">Submit</button>
				</div>
			</div>-->
		</form>
	</div>
	
 <div class="row" >
			 	<div class="col-md-6 ">
			 			<a href=""><img  src="{% static 'img/notificacion.png' %}" class="img-circle center-block" style="width: 40%"></a>
			 	</div>
			 	<div class="col-md-6">
						<a href=""><img src="{% static 'img/buscar.png' %}" class="img-circle center-block" style="width: 40%"></a>
			 	</div>
			 </div>
			 <div class="row">
			 	<div class="col-md-6">
			 			<a href="" id="lol"><img src="{% static 'img/configuracion.png' %}" class="img-circle center-block" style="width: 40%"></a>
			 	</div>
			 	<div class="col-md-6">
			 			<a href="" id="lol2"><img src="{% static 'img/chat.png' %}" class="img-circle center-block" style="width: 40%"></a>
			 	</div>
			 </div>
			 <div class="row">
			 	<div class="col-md-6">
			 			<a href=""><img src="{% static 'img/warning.png' %}" class="img-circle center-block" style="width: 40%"></a>

			 	</div>
			 	<div class="col-md-6">
			 			<a href=""><img src="{% static 'img/historial.png' %}" class="img-circle center-block" style="width: 40%"></a>


			 	</div>
			 </div>
		

	<!-- modelo= models.CharField(max_length=264)
	plazas= models.CharField(max_length=264)
	aire_acondicionado= models.CharField(max_length=264)
	tipo_transmision= models.CharField(max_length=264)
	lugar_recodiga= models.CharField(max_length=264)
	precio= models.FloatField()
	jornada= models.IntegerField(max_length=264)
	is_alquiled= models.BooleanField() -->
	{% if access_records %}
	<section>
		<h2>Recomendados</h2>
		{% for acc in access_records %}
		<div class="row">
			<div class="col-md-4">
				<a href=""><img src="{% static 'img/car.jpg' %}" class="img-thumbnail"></a>
			</div>
			<div class="col-md-4">
				<h2>{{acc.modelo}}</h2>
				<p><strong>plazas: </strong>{{acc.plazas}}</p>
				<p><strong>Aire Acondicionado: </strong>{{acc.aire_acondicionado}}</p>
				<p><strong>Tipo Transmision: </strong>{{acc.tipo_transmision}}</p>
				<p><strong>Lugar Recogida: </strong>{{acc.lugar_recodiga}}</p>
			</div>
			<div class="col-md-4">
				<h2> Precio por jornada de {{acc.jornada}} horas</h2>
				<h1>S/.{{acc.precio}}</h1>
			</div>
		</div>
		{% endfor %}
	</section>
	{% endif %}
</div>

{% endblock%}

issy_web/conductor/templates/conductor/review_create.html
{% extends "base.html" %}

{% load bootstrap3 %}

{% block content %}

<div class="container"> 
	<h4>comentario al usuario</h4>

		<form method="POST" action="" id="postForm">
			{% csrf_token %}
			{% bootstrap_form form %}
			<input type="submit" value="Post" class="btn btn-primary btn-large">
		</form>
	
</div>
{% endblock %}

issy_web/conductor/templates/index.html
{% extends "base.html"%}

{% load staticfiles%}

{% block content %}

<div class="jumbotron">
		<div class="container">
			<div class="row">
				<div class="col-md-6">
					<h1>Captura un <span class="em-text">Conductor</span></h1>
					<p>Una forma rápida y sencilla de buscar autos y conductores - Izi carro Izi life</p>
					<a href="{% url 'conductor:alquilar_auto' %}" ><img class="app-btn img-rounded"  id="botoncarro" src="{% static 'img/drivericon2.jpg' %}"></a>
					<a href="{% url 'conductor:alquilar_auto' %}"><img class="app-btn img-rounded" id="botoncarro" src="{% static 'img/drivericon.jpg' %}"></a>
				</div>
				<div class="col-md-6">
			
					<img src="{% static 'img/site_phone2.png' %}" class="showcase-img">
				</div>
			</div>
		</div>
	</div>
	<section id="middle">
		<div class="container">
			<div class="row">
				<div class="col-md-4">
					<img src="{% static 'img/carpublicidad.png' %}" class="demo">
					<h2>Seguro de autos</h2>
					<p>Encuentra en segundos el seguro vehicular que necesitas. Te asesoramos antes y después de la contratación de tu seguro para que compares todas las opciones del mercado y ahorres hasta 35%.</p>
					<a href="#" class="btn btn-default">
						Read more..
					</a>

				</div>
				<div class="col-md-4">
					<img src="{% static 'img/carpublicidad.jpg' %}" class="demo">
					<h2>¿Quieres cambiar de auto?</h2>
					<p>Si decides cambiar tu coche a través de particulares, corres el riesgo de que la venta de tu coche se haga por otro precio al deseado y que se demore más de lo que piensas. Si prefieres profesionales, lo harás más rápido pero asegúrate de que te dan el precio real de tu coche en el mercado y, sobre todo, evita pagar los costes de tasación de tu vehículo y confirma antes que no te exigen compromiso de venta.La forma más rápida y fiable de vender tu automóvil es en compramostucoche.es. Sin anuncios, sin regateos, sin costes, sin compromiso y sin trámites como el cambio de titularidad. Tasa ahora tu coche online de forma gratuita y conoce el valor aproximado del mismo en cinco minutos.</p>
					<a href="#" class="btn btn-default">
						Read more
					</a>

				</div>
				<div class="col-md-4">
					<img src="{% static 'img/carpublicidad2.jpg' %}" class="demo">
					<h2>Consigue autos nuevos</h2>
					<p>Ingresa a nuestro catálogo de autos nuevos y adquirí el auto que tanto soñaste! Precios, ofertas, cotizaciones y planes de financiación en Perú. Todos los autos nuevos disponibles en el mercado. Encuentra la información más completa de equipamiento, colores, precios, datos técnicos y fotos de todos los autos.</p>
					<a href="#" class="btn btn-default">
						Read more
					</a>

				</div>
			</div>
		</div>
	</section>
	<section id="feature">
		<div class="container">
			<div class="row">
				<div class="col-md-5">
					<h1>Ventajas de Issy Car</h1>
					<ul>
						<li><i class="glyphicon glyphicon-ok"></i>Intuitivo </li>
						<li><i class="glyphicon glyphicon-ok"></i>Rápido </li>
						<li><i class="glyphicon glyphicon-ok"></i>Seguro </li>
						<li><i class="glyphicon glyphicon-ok"></i>Confiable</li>
					</ul>
				</div>
				<div class="col-md-4 col-md-offset-2">
					<img src="{% static 'img/logo2.png' %}" class="big-logo">		
				</div>
			</div>
		</div>
	</section>

{% endblock%}

issy_web/conductor/templates/test.html
{%extends "base.html"%}
{% block content%}
<h1>You are Login</h1>
{% endblock%}

issy_web/conductor/templates/thanks.html
{%extends "base.html"%}
{% block content%}
<h1>Thanks for visiting, come back soon!</h1>

{% endblock%}